### ISSUE TITLE
Suggest new fonction

### ISSUE THREAD

**Issue by Percherie** [lorenzo-deluca/homeassistant-silence#11]
Great work

I'm trying to record the movements to display them on the map.

I can imagine the following scenarios:
1. Identify when the scooter is powered up, even if it is not moving, in order to limit the selections.
2. Convert the history of coordinates into gpx tracks. With a different track each time the scooter is switched off.
3. Automatically save tracks as gpx files for display on the map and for historical purposes.
4. On the map, put a drop-down menu to choose your track file and display it.
5. Bonus: download the selected gpx track.
6. Second bonus: be able to display several tracks (map analysis, simplified history preview).

I know it's very complex but I can help (DIY level) or test, provide rendering sketches, look for tips on gpx files (advanced level).

If you're interested in this proposal, where would you like to start?

**Comment by lorenzo-deluca** [comment]
Hello @Percherie, sorry for the delay, good ideas ;)
If you are interested, I used [Traccar ](https://www.traccar.org) to do what you say ;)

1. Install a Traccar instance on my Raspberry
2. Create a device on Traccar with the ID the same id of scooter device tracker, in my case "device_tracker.silence_scooter_tracker"
3. Create a custom API command in HA
```yaml
rest_command:
  update_traccar:
    url: 'http://<ip>:<port>'
    method: GET
    payload: '?id={{id}}&lat={{lat}}&lon={{lon}}&altitude={{alt}}&batt={{batt}}&speed={{speed}}'
```
4. Create/update an automation, [like say here](https://github.com/lorenzo-deluca/homeassistant-silence#device-tracker)
and add rest_command service call

```yaml
 - service: rest_command.update_traccar
    continue_on_error: true
    data:
      id: device_tracker.silence_scooter_tracker
      lat: '{{ states(''sensor.silence_location_latitude'') }}'
      lon: '{{ states(''sensor.silence_location_longitude'') }}'
      alt: '0'
      batt: '{{ states(''sensor.silence_soc'') | int }}'
      speed: '{{ states(''sensor.silence_velocity'') | int }}'
```

5. Now you have your scooter tracked 24/7 on Traccar ;)
![image](https://github.com/lorenzo-deluca/homeassistant-silence/assets/32000123/3b899f1d-88fc-4949-8825-2b360835e4cf)

What do you think about this solution?

If you would like to contribute to the project and would like to write a guide on how to integrate everything :)
